package modules

import "github.com/sanchezsase1991-sys/Nexo_ss/internal/bus"

var ToolRegistry = map[bus.ToolName]bus.ToolCapability{
	bus.ToolBattery:          {Name: bus.ToolBattery, Keywords: []string{"batería", "battery", "carga", "nivel", "porcentaje"}, Params: []bus.ToolParam{}, Description: "Obtiene el nivel de batería", Category: "device", RequiresAuth: false},
	bus.ToolLocation:         {Name: bus.ToolLocation, Keywords: []string{"ubicación", "gps", "dónde estoy", "localización", "posición"}, Params: []bus.ToolParam{}, Description: "Obtiene ubicación actual", Category: "device", RequiresAuth: true},
	bus.ToolDevice:           {Name: bus.ToolDevice, Keywords: []string{"dispositivo", "modelo", "información", "device info"}, Params: []bus.ToolParam{}, Description: "Información del dispositivo", Category: "device", RequiresAuth: false},
	bus.ToolWifi:             {Name: bus.ToolWifi, Keywords: []string{"wifi", "internet", "red", "ip", "conexión"}, Params: []bus.ToolParam{}, Description: "Estado de conexión WiFi", Category: "network", RequiresAuth: false},
	bus.ToolClipboardGet:     {Name: bus.ToolClipboardGet, Keywords: []string{"clipboard", "portapapeles", "copiado", "pegar"}, Params: []bus.ToolParam{}, Description: "Lee el portapapeles", Category: "system", RequiresAuth: false},
	bus.ToolRead:             {Name: bus.ToolRead, Keywords: []string{"lee", "archivo", "contenido", "muestra", "abrir"}, Params: []bus.ToolParam{{Name: "path", Type: "string", Required: true, Description: "Ruta del archivo"}}, Description: "Lee contenido de archivo", Category: "filesystem", RequiresAuth: false},
	bus.ToolShell:            {Name: bus.ToolShell, Keywords: []string{"bash", "comando", "ejecuta", "terminal", "shell", "cmd"}, Params: []bus.ToolParam{{Name: "command", Type: "string", Required: true, Description: "Comando a ejecutar"}}, Description: "Ejecuta comando en shell", Category: "system", RequiresAuth: true},
	bus.ToolCamera:           {Name: bus.ToolCamera, Keywords: []string{"cámara", "camera", "foto", "captura", "fotografía"}, Params: []bus.ToolParam{}, Description: "Abre la cámara", Category: "hardware", RequiresAuth: true},
	bus.ToolTorchOn:          {Name: bus.ToolTorchOn, Keywords: []string{"linterna", "luz", "flashlight", "encender", "iluminar"}, Params: []bus.ToolParam{}, Description: "Enciende la linterna", Category: "hardware", RequiresAuth: false},
	bus.ToolTorchOff:         {Name: bus.ToolTorchOff, Keywords: []string{"apagar linterna", "luz off", "flashlight off"}, Params: []bus.ToolParam{}, Description: "Apaga la linterna", Category: "hardware", RequiresAuth: false},
	bus.ToolToast:            {Name: bus.ToolToast, Keywords: []string{"toast", "popup", "mensaje flotante", "notificación rápida"}, Params: []bus.ToolParam{{Name: "message", Type: "string", Required: true, Description: "Mensaje a mostrar"}}, Description: "Muestra un toast", Category: "ui", RequiresAuth: false},
	bus.ToolTTS:              {Name: bus.ToolTTS, Keywords: []string{"voz", "habla", "texto a voz", "tts", "speak", "di"}, Params: []bus.ToolParam{{Name: "text", Type: "string", Required: true, Description: "Texto a convertir"}}, Description: "Convierte texto a voz", Category: "output", RequiresAuth: false},
	bus.ToolVibrate:          {Name: bus.ToolVibrate, Keywords: []string{"vibra", "vibración", "vibrate"}, Params: []bus.ToolParam{{Name: "duration_ms", Type: "int", Required: false, Default: "500", Description: "Duración en ms"}}, Description: "Vibración del dispositivo", Category: "hardware", RequiresAuth: false},
	bus.ToolNotification:     {Name: bus.ToolNotification, Keywords: []string{"notificación", "avísame", "recordatorio", "alerta"}, Params: []bus.ToolParam{{Name: "title", Type: "string", Required: true}, {Name: "message", Type: "string", Required: true}}, Description: "Envía notificación", Category: "ui", RequiresAuth: false},
	bus.ToolIntentView:       {Name: bus.ToolIntentView, Keywords: []string{"abre", "navegador", "http", "url", "web"}, Params: []bus.ToolParam{{Name: "url", Type: "string", Required: true, Description: "URL a abrir"}}, Description: "Abre URL en navegador", Category: "intent", RequiresAuth: false},
	bus.ToolIntentDial:       {Name: bus.ToolIntentDial, Keywords: []string{"llama", "llamar", "teléfono", "marca", "dial"}, Params: []bus.ToolParam{{Name: "number", Type: "string", Required: true, Description: "Número telefónico"}}, Description: "Abre marcador telefónico", Category: "intent", RequiresAuth: true},
	bus.ToolIntentSettings:   {Name: bus.ToolIntentSettings, Keywords: []string{"configuración", "ajustes", "settings"}, Params: []bus.ToolParam{}, Description: "Abre configuración", Category: "intent", RequiresAuth: false},
	bus.ToolIntentAlarm:      {Name: bus.ToolIntentAlarm, Keywords: []string{"alarma", "despertador", "alarm"}, Params: []bus.ToolParam{{Name: "hour", Type: "int", Required: true}, {Name: "minute", Type: "int", Required: true}}, Description: "Configura alarma", Category: "intent", RequiresAuth: false},
	bus.ToolShizuku:          {Name: bus.ToolShizuku, Keywords: []string{"shizuku", "root", "adb", "privilegio"}, Params: []bus.ToolParam{{Name: "command", Type: "string", Required: true}}, Description: "Ejecuta vía Shizuku", Category: "system", RequiresAuth: true},
	bus.ToolNexoUIDump:       {Name: bus.ToolNexoUIDump, Keywords: []string{"ui dump", "pantalla actual", "elementos ui"}, Params: []bus.ToolParam{}, Description: "Vuelca jerarquía UI", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoScreencap:    {Name: bus.ToolNexoScreencap, Keywords: []string{"screenshot", "captura pantalla", "pantalla"}, Params: []bus.ToolParam{}, Description: "Captura pantalla", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoInputTap:     {Name: bus.ToolNexoInputTap, Keywords: []string{"tap", "tocar", "click", "presionar"}, Params: []bus.ToolParam{{Name: "x", Type: "int", Required: true}, {Name: "y", Type: "int", Required: true}}, Description: "Simula tap", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoInputText:    {Name: bus.ToolNexoInputText, Keywords: []string{"escribir", "texto", "input text", "type"}, Params: []bus.ToolParam{{Name: "text", Type: "string", Required: true}}, Description: "Ingresa texto", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoInputKeyevent:{Name: bus.ToolNexoInputKeyevent, Keywords: []string{"tecla", "keyevent", "botón", "presionar tecla"}, Params: []bus.ToolParam{{Name: "keycode", Type: "int", Required: true}}, Description: "Simula tecla", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoIntent:       {Name: bus.ToolNexoIntent, Keywords: []string{"intent", "lanzar", "actividad"}, Params: []bus.ToolParam{{Name: "action", Type: "string", Required: true}, {Name: "data", Type: "string", Required: false}}, Description: "Lanza intent Android", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoBsh:          {Name: bus.ToolNexoBsh, Keywords: []string{"bsh", "beanshell", "script"}, Params: []bus.ToolParam{{Name: "script", Type: "string", Required: true}}, Description: "Ejecuta BeanShell", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoBshExpr:      {Name: bus.ToolNexoBshExpr, Keywords: []string{"bsh expr", "expresión", "evaluar"}, Params: []bus.ToolParam{{Name: "expression", Type: "string", Required: true}}, Description: "Evalúa expresión BeanShell", Category: "nexo_mcp", RequiresAuth: true},
	bus.ToolNexoContentQuery: {Name: bus.ToolNexoContentQuery, Keywords: []string{"content query", "consulta contenido", "provider"}, Params: []bus.ToolParam{{Name: "uri", Type: "string", Required: true}, {Name: "projection", Type: "string", Required: false}}, Description: "Consulta ContentProvider", Category: "nexo_mcp", RequiresAuth: true},
}
